apiVersion: apps/v1
kind: Deployment
metadata:
  name: character-catalog-webapi-prod
  namespace: character-catalog-prod
  labels:
    app: character-catalog-webapi-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: character-catalog-webapi-prod
  template:
    metadata:
      labels:
        app: character-catalog-webapi-prod
    spec:
      containers:
        - name: character-catalog-webapi
          image: ghcr.io/szodas/alkfejl-character-catalog/character-catalog-webapi:latest
          imagePullPolicy: Always
          env:
            - name: MongoDb__ConneX
              valueFrom:
                secretKeyRef:
                  name: character-catalog-secrets-prod
                  key: mongodb-url
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: character-catalog-webapi-prod
  namespace: character-catalog-prod
spec:
  selector:
    app: character-catalog-webapi-prod
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30081
  type: NodePort