apiVersion: apps/v1
kind: Deployment
metadata:
  name: character-catalog-webui-prod
  namespace: character-catalog-prod
  labels:
    app: character-catalog-webui-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: character-catalog-webui-prod
  template:
    metadata:
      labels:
        app: character-catalog-webui-prod
    spec:
      containers:
      - name: character-catalog-webui
        image: ghcr.io/szodas/alkfejl-character-catalog/character-catalog-webui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: character-catalog-webui-prod
  namespace: character-catalog-prod
spec:
  selector:
    app: character-catalog-webui-prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort